### ISSUE TITLE
What was the last problem you gave up on?

### ISSUE THREAD

**Issue by sholladay** [AchoArnold/ama#18]
We all face problems that we don't solve for various reasons (i.e. time, money, motivation). What was the most recent problem that you gave up on and why? Do you intend to resume working on it soon? What goes into that decision? Are you feeling pressured or lazy about it?

**Comment by AchoArnold** [comment]
**The most recent problem that you gave up on and why?**

Well for a non programming problem, I usually eat my fingernails and I decided to stop. I was working on quitting this bad habit before I gave up due to lack of motivation.

**Do you intend to resume working on it soon?**

Yes. Thanks for the question, It has reminded me of it and I intend to start working on it as from now.

**What goes into that decision?**

I'm really don't like when my fingernails look bad and I'll love to stop this bad habbit of mine


**Are you feeling pressured or lazy about it?**

I'm feeling lazy about it ;)


**Thanks for the question**
